services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: quiz_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

  question_service:
    build:
      context: ./question_service
    container_name: question_service
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  submit_service:
    build:
      context: ./submit_service
    container_name: submit_service
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
