services:
  mongo:
    image: mongo:latest
    container_name: quizdb-mongo
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: always

  question-service:
    build:
      context: ./question-service
    container_name: question-service
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

  submit-service:
    build:
      context: ./submit-service
    container_name: submit-service
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - mongo

volumes:
  mongodb-data:
    driver: local

networks:
  app-network:
    driver: bridge
