services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    restart: always
    ports:
      - "4002:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: quiz_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

  question_service:
    # Uncomment the following lines to build the container locally
    #build:
       #context: ./question_service
       #dockerfile: Dockerfile
    image: smileyjam/question_service:3rdClass
    container_name: question_service
    ports:
      - "4000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  submit_service:
    # Uncomment the following lines to build the container locally
    #build:
     #  context: ./submit_service
      # dockerfile: Dockerfile
    image: smileyjam/submit_service:3rdClass
    container_name: submit_service
    ports:
      - "4200:3200"
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge